spring.application.name=spring-boot
management.endpoints.web.exposure.include = *

#management.endpoints.web.exposure.exclude = health,info
management.info.env.enabled = true

info.app.name = name of information
info.app.description =description of app